# backend/app/core/feature_space.py
FEATURE_SPACE = [
    # ======== GENRES ========
    "genre_action",
    "genre_adventure",
    "genre_animation",
    "genre_comedy",
    "genre_crime",
    "genre_documentary",
    "genre_drama",
    "genre_fantasy",
    "genre_historical",
    "genre_horror",
    "genre_mystery",
    "genre_romance",
    "genre_sci_fi",
    "genre_thriller",
    "genre_war",
    "genre_western",

    # ======== MOODS ========
    "mood_happy",
    "mood_sad",
    "mood_romantic",
    "mood_angry",
    "mood_anxious",
    "mood_calm",
    "mood_confused",
    "mood_depressed",
    "mood_excited",
    "mood_fearful",
    "mood_gloomy",
    "mood_hopeful",
    "mood_lonely",
    "mood_nostalgic",
    "mood_peaceful",
    "mood_sentimental",
    "mood_stressed",
    "mood_tense",

    # ======== TONES ========
    "tone_dark",
    "tone_light",
    "tone_epic",
    "tone_gritty",
    "tone_whimsical",
    "tone_satirical",
    "tone_serious",
    "tone_witty",
    "tone_bleak",
    "tone_uplifting",
    "tone_ironic",
    "tone_melancholic",
    "tone_suspenseful",
    "tone_emotional",
    "tone_thoughtful",

    # ======== SETTINGS ========
    "setting_historical",
    "setting_future",
    "setting_space",
    "setting_urban",
    "setting_rural",
    "setting_suburban",
    "setting_dystopian",
    "setting_apocalyptic",
    "setting_steampunk",
    "setting_cyberpunk",
    "setting_medieval",
    "setting_victorian",
    "setting_western",
    "setting_modern",
    "setting_fantasy",

    # ======== THEMES ========
    "theme_love",
    "theme_war",
    "theme_family",
    "theme_revenge",
    "theme_survival",
    "theme_friendship",
    "theme_redemption",
    "theme_crime",
    "theme_coming_of_age",
    "theme_betrayal",
    "theme_justice",
    "theme_identity",
    "theme_isolation",
    "theme_morality",
    "theme_sacrifice",

    # ======== PACING ========
    "pacing_fast",
    "pacing_medium",
    "pacing_slow",
    "pacing_variable"
]

# Maintain existing mapping structure
TRAIT_MAPPING = {trait: idx for idx, trait in enumerate(FEATURE_SPACE)}